// pages/journey.vue
<template>
  <div class="min-h-screen bg-stone-50 pb-24 pt-8 md:pt-12 px-4">
    <div class="max-w-4xl mx-auto">
      <PageHeader
        title="Our Journey"
        subtitle="Tracing the footsteps of devotion that led us to this momentous milestone."
      />

      <ClientOnly>
        <div v-if="isLoading" class="flex min-h-[40vh] items-center justify-center text-[hsl(var(--muted-foreground))]">
          Loading Journey...
        </div>
        <div v-else-if="error" class="flex min-h-[40vh] flex-col items-center justify-center gap-2 text-red-600">
          <p class="font-medium">Failed to load timeline</p>
          <p class="text-sm text-center text-[hsl(var(--muted-foreground))] max-w-md">{{ error.message }}</p>
        </div>
        <div v-else class="relative mt-12">
          <div class="absolute left-4 md:left-1/2 top-0 bottom-0 w-0.5 bg-gradient-to-b from-[hsl(var(--primary))]/10 via-[hsl(var(--primary))]/40 to-[hsl(var(--primary))]/10 transform md:-translate-x-1/2" />
          <div class="space-y-12">
            <div
              v-for="(item, index) in timeline"
              :key="item.id"
              class="relative flex flex-col md:flex-row gap-8"
              :class="index % 2 === 0 ? 'md:flex-row-reverse' : ''"
            >
              <div class="absolute left-4 md:left-1/2 w-8 h-8 rounded-full bg-white border-4 border-[hsl(var(--primary))] shadow-lg transform -translate-x-1/2 z-10 flex items-center justify-center">
                <div class="w-2 h-2 rounded-full bg-[hsl(var(--primary))]" />
              </div>
              <div class="ml-12 md:ml-0 md:w-1/2 md:px-8">
                <div
                  class="bg-white p-6 rounded-2xl shadow-sm border border-[hsl(var(--golden-200))] hover:shadow-md transition-shadow"
                  :class="index % 2 === 0 ? 'text-left' : 'md:text-right'"
                >
                  <span class="inline-block px-3 py-1 bg-[hsl(var(--golden-50))] text-[hsl(var(--foreground))] text-xs font-bold rounded-full mb-3">
                    {{ item.year }}
                  </span>
                  <h3 class="text-xl font-bold text-[hsl(var(--foreground))] mb-2">{{ item.title }}</h3>
                  <p class="text-[hsl(var(--muted-foreground))] leading-relaxed text-sm">{{ item.description }}</p>
                  <div v-if="item.imageUrl" class="mt-4 rounded-lg overflow-hidden h-40 w-full relative">
                    <img
                      :src="item.imageUrl"
                      :alt="item.title"
                      class="w-full h-full object-cover"
                      @error="($event.target as HTMLImageElement).src = 'https://images.unsplash.com/photo-1545638100-249071c33c37?w=800&auto=format&fit=crop&q=60'"
                    >
                  </div>
                </div>
              </div>
              <div class="md:w-1/2" />
            </div>
          </div>
        </div>
        <template #fallback>
          <div class="flex min-h-[40vh] items-center justify-center text-[hsl(var(--muted-foreground))]">
            Loading Journey...
          </div>
        </template>
      </ClientOnly>
    </div>
  </div>
</template>

<script setup lang="ts">
const { timeline, isLoading, error } = useTimeline()
</script>

// client/src/pages/Journey.tsx
import { PageHeader } from "@/components/PageHeader";
import { useTimeline } from "@/hooks/use-mandir";
import { motion } from "framer-motion";

export default function Journey() {
  const { data: timeline, isLoading, error } = useTimeline();

  if (isLoading) return <div className="min-h-screen flex items-center justify-center text-muted-foreground">Loading Journey...</div>;
  if (error) return <div className="min-h-screen flex items-center justify-center text-red-500">Failed to load timeline</div>;

  return (
    <div className="min-h-screen bg-stone-50 pb-24 pt-8 md:pt-12 px-4">
      <div className="max-w-4xl mx-auto">
        <PageHeader 
          title="Our Journey" 
          subtitle="Tracing the footsteps of devotion that led us to this momentous milestone." 
        />

        <div className="relative mt-12">
          {/* Vertical Line */}
          <div className="absolute left-4 md:left-1/2 top-0 bottom-0 w-0.5 bg-gradient-to-b from-primary/10 via-primary/40 to-primary/10 transform md:-translate-x-1/2" />

          <div className="space-y-12">
            {timeline?.map((item, index) => (
              <motion.div
                key={item.id}
                initial={{ opacity: 0, y: 50 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className={`relative flex flex-col md:flex-row gap-8 ${
                  index % 2 === 0 ? "md:flex-row-reverse" : ""
                }`}
              >
                {/* Year Bubble */}
                <div className="absolute left-4 md:left-1/2 w-8 h-8 rounded-full bg-white border-4 border-primary shadow-lg transform -translate-x-1/2 z-10 flex items-center justify-center">
                   <div className="w-2 h-2 rounded-full bg-primary" />
                </div>

                {/* Content */}
                <div className="ml-12 md:ml-0 md:w-1/2 md:px-8">
                  <div className={`bg-white p-6 rounded-2xl shadow-sm border border-golden-200 hover:shadow-md transition-shadow ${
                    index % 2 === 0 ? "text-left" : "md:text-right"
                  }`}>
                    <span className="inline-block px-3 py-1 bg-golden-50 text-foreground text-xs font-bold rounded-full mb-3">
                      {item.year}
                    </span>
                    <h3 className="text-xl font-bold text-foreground mb-2">{item.title}</h3>
                    <p className="text-muted-foreground leading-relaxed text-sm">{item.description}</p>
                    
                    {item.imageUrl && (
                      <div className="mt-4 rounded-lg overflow-hidden h-40 w-full relative">
                        {/* Descriptive comment for Unsplash fallback */}
                        {/* Mandir construction or celebration or devotional gathering */}
                        <img 
                          src={item.imageUrl} 
                          alt={item.title}
                          className="w-full h-full object-cover" 
                          onError={(e) => {
                            e.currentTarget.src = "https://images.unsplash.com/photo-1545638100-249071c33c37?w=800&auto=format&fit=crop&q=60";
                          }}
                        />
                      </div>
                    )}
                  </div>
                </div>
                
                {/* Empty space for the other side */}
                <div className="md:w-1/2" />
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
