// components/PageHeader.vue
<template>
  <div
    class="mb-8 text-center"
    :class="className"
  >
    <h1 class="text-3xl md:text-4xl font-bold text-[hsl(var(--foreground))] mb-2">
      {{ title }}
    </h1>
    <p v-if="subtitle" class="text-[hsl(var(--muted-foreground))] max-w-lg mx-auto leading-relaxed">
      {{ subtitle }}
    </p>
    <div class="mt-4 mx-auto w-16 h-1 bg-gradient-to-r from-transparent via-[hsl(var(--primary))] to-transparent rounded-full" />
  </div>
</template>

<script setup lang="ts">
defineProps<{
  title: string
  subtitle?: string
  className?: string
}>()
</script>

// client/src/components/PageHeader.tsx
import { motion } from "framer-motion";

interface PageHeaderProps {
  title: string;
  subtitle?: string;
  className?: string;
}

export function PageHeader({ title, subtitle, className = "" }: PageHeaderProps) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: -20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, ease: "easeOut" }}
      className={`mb-8 text-center ${className}`}
    >
      <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-2">{title}</h1>
      {subtitle && (
        <p className="text-muted-foreground max-w-lg mx-auto leading-relaxed">{subtitle}</p>
      )}
      <div className="mt-4 mx-auto w-16 h-1 bg-gradient-to-r from-transparent via-primary to-transparent rounded-full" />
    </motion.div>
  );
}
